<?php

namespace Modules\Content\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;

use App\Entities\TaxonomyManager;

class CallCodesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Model::unguard();

        $callcodes = [
            '+93' => ['country'=>'Afghanistan'],
            '+355' => ['country'=>'Albania'],
            '+213' => ['country'=>'Algeria'],
            '+1 684' => ['country'=>'American Samoa'],
            '+376' => ['country'=>'Andorra'],
            '+244' => ['country'=>'Angola'],
            '+1 264' => ['country'=>'Anguilla'],
            '+6721' => ['country'=>'Antarctica (Australian bases)'],
            '+1 268' => ['country'=>'Antigua and Barbuda'],
            '+54' => ['country'=>'Argentina'],
            '+374' => ['country'=>'Armenia'],
            '+297' => ['country'=>'Aruba'],
            '+247' => ['country'=>'Ascension'],
            '+61' => ['country'=>'Australia'],
            '+43' => ['country'=>'Austria'],
            '+994' => ['country'=>'Azerbaijan'],
            '+1 242' => ['country'=>'Bahamas'],
            '+973' => ['country'=>'Bahrain'],
            '+880' => ['country'=>'Bangladesh'],
            '+1 246' => ['country'=>'Barbados'],
            '+375' => ['country'=>'Belarus'],
            '+32' => ['country'=>'Belgium'],
            '+501' => ['country'=>'Belize'],
            '+229' => ['country'=>'Benin'],
            '+1 441' => ['country'=>'Bermuda'],
            '+975' => ['country'=>'Bhutan'],
            '+591' => ['country'=>'Bolivia'],
            '+387' => ['country'=>'Bosnia and Herzegovina'],
            '+267' => ['country'=>'Botswana'],
            '+55' => ['country'=>'Brazil'],
            '+246' => ['country'=>'British Indian Ocean Territory'],
            '+1 284' => ['country'=>'British Virgin Islands'],
            '+673' => ['country'=>'Brunei'],
            '+359' => ['country'=>'Bulgaria'],
            '+226' => ['country'=>'Burkina Faso'],
            '+257' => ['country'=>'Burundi'],
            '+855' => ['country'=>'Cambodia'],
            '+237' => ['country'=>'Cameroon'],
            '+1' => ['country'=>'Canada'],
            '+238' => ['country'=>'Cape Verde'],
            '+1 345' => ['country'=>'Cayman Islands'],
            '+236' => ['country'=>'Central African Republic'],
            '+235' => ['country'=>'Chad'],
            '+56' => ['country'=>'Chile'],
            '+86' => ['country'=>'China'],
            '+57' => ['country'=>'Colombia'],
            '+269' => ['country'=>'Comoros'],
            '+243' => ['country'=>'Congo, Democratic Republic of the'],
            '+242' => ['country'=>'Congo, Republic of the'],
            '+682' => ['country'=>'Cook Islands'],
            '+506' => ['country'=>'Costa Rica'],
            '+225' => ['country'=>'Cote d’Ivoire'],
            '+385' => ['country'=>'Croatia'],
            '+53' => ['country'=>'Cuba'],
            '+599' => ['country'=>'Curaçao'],
            '+357' => ['country'=>'Cyprus'],
            '+420' => ['country'=>'Czech Republic'],
            '+45' => ['country'=>'Denmark'],
            '+253' => ['country'=>'Djibouti'],
            '+1 767' => ['country'=>'Dominica'],
            '+849' => ['country'=>'Dominican Republic'],
            '+670' => ['country'=>'East Timor'],
            '+593' => ['country'=>'Ecuador'],
            '+20' => ['country'=>'Egypt'],
            '+503' => ['country'=>'El Salvador'],
            '+240' => ['country'=>'Equatorial Guinea'],
            '+291' => ['country'=>'Eritrea'],
            '+372' => ['country'=>'Estonia'],
            '+251' => ['country'=>'Ethiopia'],
            '+500' => ['country'=>'Falkland Islands'],
            '+298' => ['country'=>'Faroe Islands'],
            '+679' => ['country'=>'Fiji'],
            '+358' => ['country'=>'Finland'],
            '+33' => ['country'=>'France'],
            '+594' => ['country'=>'French Guiana'],
            '+689' => ['country'=>'French Polynesia'],
            '+241' => ['country'=>'Gabon'],
            '+220' => ['country'=>'Gambia'],
            '+970' => ['country'=>'Gaza Strip'],
            '+995' => ['country'=>'Georgia'],
            '+49' => ['country'=>'Germany'],
            '+233' => ['country'=>'Ghana'],
            '+350' => ['country'=>'Gibraltar'],
            '+30' => ['country'=>'Greece'],
            '+299' => ['country'=>'Greenland'],
            '+1 473' => ['country'=>'Grenada'],
            '+590' => ['country'=>'Guadeloupe'],
            '+1 671' => ['country'=>'Guam'],
            '+502' => ['country'=>'Guatemala'],
            '+224' => ['country'=>'Guinea'],
            '+245' => ['country'=>'Guinea-Bissau'],
            '+592' => ['country'=>'Guyana'],
            '+509' => ['country'=>'Haiti'],
            '+504' => ['country'=>'Honduras'],
            '+852' => ['country'=>'Hong Kong'],
            '+36' => ['country'=>'Hungary'],
            '+354' => ['country'=>'Iceland'],
            '+91' => ['country'=>'India'],
            '+62' => ['country'=>'Indonesia'],
            '+964' => ['country'=>'Iraq'],
            '+98' => ['country'=>'Iran'],
            '+353' => ['country'=>'Ireland (Eire)'],
            '+972' => ['country'=>'Israel'],
            '+39' => ['country'=>'Italy'],
            '+1 876' => ['country'=>'Jamaica'],
            '+81' => ['country'=>'Japan'],
            '+962' => ['country'=>'Jordan'],
            '+7' => ['country'=>'Kazakhstan'],
            '+254' => ['country'=>'Kenya'],
            '+686' => ['country'=>'Kiribati'],
            '+386' => ['country'=>'Kosovo 377, 381,'],
            '+965' => ['country'=>'Kuwait'],
            '+996' => ['country'=>'Kyrgyzstan'],
            '+856' => ['country'=>'Laos'],
            '+371' => ['country'=>'Latvia'],
            '+961' => ['country'=>'Lebanon'],
            '+266' => ['country'=>'Lesotho'],
            '+231' => ['country'=>'Liberia'],
            '+218' => ['country'=>'Libya'],
            '+423' => ['country'=>'Liechtenstein'],
            '+370' => ['country'=>'Lithuania'],
            '+352' => ['country'=>'Luxembourg'],
            '+853' => ['country'=>'Macau'],
            '+389' => ['country'=>'Macedonia, Republic of'],
            '+261' => ['country'=>'Madagascar'],
            '+265' => ['country'=>'Malawi'],
            '+60' => ['country'=>'Malaysia'],
            '+960' => ['country'=>'Maldives'],
            '+223' => ['country'=>'Mali'],
            '+356' => ['country'=>'Malta'],
            '+692' => ['country'=>'Marshall Islands'],
            '+596' => ['country'=>'Martinique'],
            '+222' => ['country'=>'Mauritania'],
            '+230' => ['country'=>'Mauritius'],
            '+262' => ['country'=>'Mayotte'],
            '+52' => ['country'=>'Mexico'],
            '+691' => ['country'=>'Micronesia, Federated States of'],
            '+373' => ['country'=>'Moldova'],
            '+377' => ['country'=>'Monaco'],
            '+976' => ['country'=>'Mongolia'],
            '+382' => ['country'=>'Montenegro'],
            '+1 664' => ['country'=>'Montserrat'],
            '+212' => ['country'=>'Morocco'],
            '+258' => ['country'=>'Mozambique'],
            '+95' => ['country'=>'Myanmar'],
            '+264' => ['country'=>'Namibia'],
            '+674' => ['country'=>'Nauru'],
            '+31' => ['country'=>'Netherlands'],
            '+599' => ['country'=>'Netherlands Antilles'],
            '+977' => ['country'=>'Nepal'],
            '+687' => ['country'=>'New Caledonia'],
            '+64' => ['country'=>'New Zealand'],
            '+505' => ['country'=>'Nicaragua'],
            '+227' => ['country'=>'Niger'],
            '+234' => ['country'=>'Nigeria'],
            '+683' => ['country'=>'Niue'],
            '+6723' => ['country'=>'Norfolk Island'],
            '+850' => ['country'=>'North Korea'],
            '+28' => ['country'=>'Northern Ireland 44'],
            '+1 670' => ['country'=>'Northern Mariana Islands'],
            '+47' => ['country'=>'Norway'],
            '+968' => ['country'=>'Oman'],
            '+92' => ['country'=>'Pakistan'],
            '+680' => ['country'=>'Palau'],
            '+507' => ['country'=>'Panama'],
            '+675' => ['country'=>'Papua New Guinea'],
            '+595' => ['country'=>'Paraguay'],
            '+51' => ['country'=>'Peru'],
            '+63' => ['country'=>'Philippines'],
            '+48' => ['country'=>'Poland'],
            '+351' => ['country'=>'Portugal'],
            '+1 939' => ['country'=>'Puerto Rico'],
            '+974' => ['country'=>'Qatar'],
            '+262' => ['country'=>'Reunion'],
            '+40' => ['country'=>'Romania'],
            '+7' => ['country'=>'Russia'],
            '+250' => ['country'=>'Rwanda'],
            '+590' => ['country'=>'Saint-Barthélemy'],
            '+290' => ['country'=>'Saint Helena'],
            '+1 869' => ['country'=>'Saint Kitts and Nevis'],
            '+1 758' => ['country'=>'Saint Lucia'],
            '+590' => ['country'=>'Saint Martin (French side)'],
            '+508' => ['country'=>'Saint Pierre and Miquelon'],
            '+1 784' => ['country'=>'Saint Vincent and the Grenadines'],
            '+685' => ['country'=>'Samoa'],
            '+239' => ['country'=>'Sao Tome and Principe'],
            '+966' => ['country'=>'Saudi Arabia'],
            '+221' => ['country'=>'Senegal'],
            '+381' => ['country'=>'Serbia'],
            '+248' => ['country'=>'Seychelles'],
            '+232' => ['country'=>'Sierra Leone'],
            '+1 721' => ['country'=>'Sint Maarten (Dutch side)'],
            '+65' => ['country'=>'Singapore'],
            '+421' => ['country'=>'Slovakia'],
            '+386' => ['country'=>'Slovenia'],
            '+677' => ['country'=>'Solomon Islands'],
            '+252' => ['country'=>'Somalia'],
            '+27' => ['country'=>'South Africa'],
            '+82' => ['country'=>'South Korea'],
            '+211' => ['country'=>'South Sudan'],
            '+34' => ['country'=>'Spain'],
            '+94' => ['country'=>'Sri Lanka'],
            '+249' => ['country'=>'Sudan'],
            '+597' => ['country'=>'Suriname'],
            '+268' => ['country'=>'Swaziland'],
            '+46' => ['country'=>'Sweden'],
            '+41' => ['country'=>'Switzerland'],
            '+963' => ['country'=>'Syria'],
            '+886' => ['country'=>'Taiwan'],
            '+992' => ['country'=>'Tajikistan'],
            '+255' => ['country'=>'Tanzania'],
            '+66' => ['country'=>'Thailand'],
            '+228' => ['country'=>'Togo'],
            '+690' => ['country'=>'Tokelau'],
            '+676' => ['country'=>'Tonga'],
            '+1 868' => ['country'=>'Trinidad and Tobago'],
            '+216' => ['country'=>'Tunisia'],
            '+90' => ['country'=>'Turkey'],
            '+993' => ['country'=>'Turkmenistan'],
            '+1 649' => ['country'=>'Turks and Caicos Islands'],
            '+688' => ['country'=>'Tuvalu'],
            '+256' => ['country'=>'Uganda'],
            '+380' => ['country'=>'Ukraine'],
            '+971' => ['country'=>'United Arab Emirates'],
            '+44' => ['country'=>'United Kingdom'],
            '+1' => ['country'=>'United States of America'],
            '+598' => ['country'=>'Uruguay'],
            '+998' => ['country'=>'Uzbekistan'],
            '+678' => ['country'=>'Vanuatu'],
            '+58' => ['country'=>'Venezuela'],
            '+84' => ['country'=>'Vietnam'],
            '+1 340' => ['country'=>'U.S. Virgin Islands'],
            '+681' => ['country'=>'Wallis and Futuna'],
            '+970' => ['country'=>'West Bank'],
            '+967' => ['country'=>'Yemen'],
            '+260' => ['country'=>'Zambia'],
            '+263' => ['country'=>'Zimbabwe']
        ];

        foreach ($callcodes as $term => $metas) {
            TaxonomyManager::register($term, 'callcodes', null, $metas);
        }
    }
}
