<?php

namespace Modules\Content\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;

use App\Managers\TaxonomyManager;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Model::unguard();

        $countries = [
            "Afghanistan"=>["officialName"=>"the Islamic Republic of Afghanistan","iso3"=>"AFG","iso2"=>"AF","uni"=>"4","undp"=>"AFG","faostat"=>"2","gaul"=>"1"],
            "Albania"=>["officialName"=>"the Republic of Albania","iso3"=>"ALB","iso2"=>"AL","uni"=>"8","undp"=>"ALB","faostat"=>"3","gaul"=>"3"],
            "Algeria"=>["officialName"=>"the People's Democratic Republic of Algeria","iso3"=>"DZA","iso2"=>"DZ","uni"=>"12","undp"=>"DZA","faostat"=>"4","gaul"=>"4"],
            "Andorra"=>["officialName"=>"the Principality of Andorra","iso3"=>"AND","iso2"=>"AD","uni"=>"20","undp"=>"AND","faostat"=>"6","gaul"=>"7"],
            "Angola"=>["officialName"=>"the Republic of Angola","iso3"=>"AGO","iso2"=>"AO","uni"=>"24","undp"=>"AGO","faostat"=>"7","gaul"=>"8"],
            "Antigua and Barbuda"=>["officialName"=>"Antigua and Barbuda","iso3"=>"ATG","iso2"=>"AG","uni"=>"28","undp"=>"ATG","faostat"=>"8","gaul"=>"11"],
            "Argentina"=>["officialName"=>"the Argentine Republic","iso3"=>"ARG","iso2"=>"AR","uni"=>"32","undp"=>"ARG","faostat"=>"9","gaul"=>"12"],
            "Armenia"=>["officialName"=>"the Republic of Armenia","iso3"=>"ARM","iso2"=>"AM","uni"=>"51","undp"=>"ARM","faostat"=>"1","gaul"=>"13"],
            "Australia"=>["officialName"=>"Australia","iso3"=>"AUS","iso2"=>"AU","uni"=>"36","undp"=>"AUS","faostat"=>"10","gaul"=>"17"],
            "Austria"=>["officialName"=>"the Republic of Austria","iso3"=>"AUT","iso2"=>"AT","uni"=>"40","undp"=>"AUT","faostat"=>"11","gaul"=>"18"],
            "Azerbaijan"=>["officialName"=>"the Republic of Azerbaijan","iso3"=>"AZE","iso2"=>"AZ","uni"=>"31","undp"=>"AZE","faostat"=>"52","gaul"=>"19"],
            "Bahamas"=>["officialName"=>"the Commonwealth of the Bahamas","iso3"=>"BHS","iso2"=>"BS","uni"=>"44","undp"=>"BHS","faostat"=>"12","gaul"=>"20"],
            "Bahrain"=>["officialName"=>"the Kingdom of Bahrain","iso3"=>"BHR","iso2"=>"BH","uni"=>"48","undp"=>"BHR","faostat"=>"13","gaul"=>"21"],
            "Bangladesh"=>["officialName"=>"the People's Republic of Bangladesh","iso3"=>"BGD","iso2"=>"BD","uni"=>"50","undp"=>"BGD","faostat"=>"16","gaul"=>"23"],
            "Barbados"=>["officialName"=>"Barbados","iso3"=>"BRB","iso2"=>"BB","uni"=>"52","undp"=>"BRB","faostat"=>"14","gaul"=>"24"],
            "Belarus"=>["officialName"=>"the Republic of Belarus","iso3"=>"BLR","iso2"=>"BY","uni"=>"112","undp"=>"BLR","faostat"=>"57","gaul"=>"26"],
            "Belgium"=>["officialName"=>"the Kingdom of Belgium","iso3"=>"BEL","iso2"=>"BE","uni"=>"56","undp"=>"BEL","faostat"=>"255","gaul"=>"27"],
            "Belize"=>["officialName"=>"Belize","iso3"=>"BLZ","iso2"=>"BZ","uni"=>"84","undp"=>"BLZ","faostat"=>"23","gaul"=>"28"],
            "Benin"=>["officialName"=>"the Republic of Benin","iso3"=>"BEN","iso2"=>"BJ","uni"=>"204","undp"=>"BEN","faostat"=>"53","gaul"=>"29"],
            "Bhutan"=>["officialName"=>"the Kingdom of Bhutan","iso3"=>"BTN","iso2"=>"BT","uni"=>"64","undp"=>"BTN","faostat"=>"18","gaul"=>"31"],
            "Bolivia (Plurinational State of)"=>["officialName"=>"the Plurinational State of Bolivia","iso3"=>"BOL","iso2"=>"BO","uni"=>"68","undp"=>"BOL","faostat"=>"19","gaul"=>"33"],
            "Bosnia and Herzegovina"=>["officialName"=>"Bosnia and Herzegovina","iso3"=>"BIH","iso2"=>"BA","uni"=>"70","undp"=>"BIH","faostat"=>"80","gaul"=>"34"],
            "Botswana"=>["officialName"=>"the Republic of Botswana","iso3"=>"BWA","iso2"=>"BW","uni"=>"72","undp"=>"BWA","faostat"=>"20","gaul"=>"35"],
            "Brazil"=>["officialName"=>"the Federative Republic of Brazil","iso3"=>"BRA","iso2"=>"BR","uni"=>"76","undp"=>"BRA","faostat"=>"21","gaul"=>"37"],
            "Brunei Darussalam"=>["officialName"=>"Brunei Darussalam","iso3"=>"BRN","iso2"=>"BN","uni"=>"96","undp"=>"BRN","faostat"=>"26","gaul"=>"40"],
            "Bulgaria"=>["officialName"=>"the Republic of Bulgaria","iso3"=>"BGR","iso2"=>"BG","uni"=>"100","undp"=>"BGR","faostat"=>"27","gaul"=>"41"],
            "Burkina Faso"=>["officialName"=>"Burkina Faso","iso3"=>"BFA","iso2"=>"BF","uni"=>"854","undp"=>"BFA","faostat"=>"233","gaul"=>"42"],
            "Burundi"=>["officialName"=>"the Republic of Burundi","iso3"=>"BDI","iso2"=>"BI","uni"=>"108","undp"=>"BDI","faostat"=>"29","gaul"=>"43"],
            "Cabo Verde"=>["officialName"=>"Republic of Cabo Verde","iso3"=>"CPV","iso2"=>"CV","uni"=>"132","undp"=>"CPV","faostat"=>"35","gaul"=>"47"],
            "Cambodia"=>["officialName"=>"the Kingdom of Cambodia","iso3"=>"KHM","iso2"=>"KH","uni"=>"116","undp"=>"KHM","faostat"=>"115","gaul"=>"44"],
            "Cameroon"=>["officialName"=>"the Republic of Cameroon","iso3"=>"CMR","iso2"=>"CM","uni"=>"120","undp"=>"CMR","faostat"=>"32","gaul"=>"45"],
            "Canada"=>["officialName"=>"Canada","iso3"=>"CAN","iso2"=>"CA","uni"=>"124","undp"=>"CAN","faostat"=>"33","gaul"=>"46"],
            "Central African Republic"=>["officialName"=>"the Central African Republic","iso3"=>"CAF","iso2"=>"CF","uni"=>"140","undp"=>"CAF","faostat"=>"37","gaul"=>"49"],
            "Chad"=>["officialName"=>"the Republic of Chad","iso3"=>"TCD","iso2"=>"TD","uni"=>"148","undp"=>"TCD","faostat"=>"39","gaul"=>"50"],
            "Chile"=>["officialName"=>"the Republic of Chile","iso3"=>"CHL","iso2"=>"CL","uni"=>"152","undp"=>"CHL","faostat"=>"40","gaul"=>"51"],
            "China"=>["officialName"=>"the People's Republic of China","iso3"=>"CHN","iso2"=>"CN","uni"=>"156","undp"=>"CHN","faostat"=>"41","gaul"=>"53"],
            "Colombia"=>["officialName"=>"the Republic of Colombia","iso3"=>"COL","iso2"=>"CO","uni"=>"170","undp"=>"COL","faostat"=>"44","gaul"=>"57"],
            "Comoros"=>["officialName"=>"the Union of the Comoros","iso3"=>"COM","iso2"=>"KM","uni"=>"174","undp"=>"COM","faostat"=>"45","gaul"=>"58"],
            "Congo"=>["officialName"=>"the Republic of the Congo","iso3"=>"COG","iso2"=>"CG","uni"=>"178","undp"=>"COG","faostat"=>"46","gaul"=>"59"],
            "Cook Islands"=>["officialName"=>"the Cook Islands","iso3"=>"COK","iso2"=>"CK","uni"=>"184","undp"=>"COK","faostat"=>"47","gaul"=>"60"],
            "Costa Rica"=>["officialName"=>"the Republic of Costa Rica","iso3"=>"CRI","iso2"=>"CR","uni"=>"188","undp"=>"CRI","faostat"=>"48","gaul"=>"61"],
            "Croatia"=>["officialName"=>"the Republic of Croatia","iso3"=>"HRV","iso2"=>"HR","uni"=>"191","undp"=>"HRV","faostat"=>"98","gaul"=>"62"],
            "Cuba"=>["officialName"=>"the Republic of Cuba","iso3"=>"CUB","iso2"=>"CU","uni"=>"192","undp"=>"CUB","faostat"=>"49","gaul"=>"63"],
            "Cyprus"=>["officialName"=>"the Republic of Cyprus","iso3"=>"CYP","iso2"=>"CY","uni"=>"196","undp"=>"CYP","faostat"=>"50","gaul"=>"64"],
            "Czechia"=>["officialName"=>"the Czech Republic","iso3"=>"CZE","iso2"=>"CZ","uni"=>"203","undp"=>"CZE","faostat"=>"167","gaul"=>"65"],
            "Côte d'Ivoire"=>["officialName"=>"the Republic of Côte d'Ivoire","iso3"=>"CIV","iso2"=>"CI","uni"=>"384","undp"=>"CIV","faostat"=>"107","gaul"=>"66"],
            "Democratic People's Republic of Korea"=>["officialName"=>"the Democratic People's Republic of Korea","iso3"=>"PRK","iso2"=>"KP","uni"=>"408","undp"=>"PRK","faostat"=>"116","gaul"=>"67"],
            "Democratic Republic of the Congo"=>["officialName"=>"the Democratic Republic of the Congo","iso3"=>"COD","iso2"=>"CD","uni"=>"180","undp"=>"COD","faostat"=>"250","gaul"=>"68"],
            "Denmark"=>["officialName"=>"the Kingdom of Denmark","iso3"=>"DNK","iso2"=>"DK","uni"=>"208","undp"=>"DNK","faostat"=>"54","gaul"=>"69"],
            "Djibouti"=>["officialName"=>"the Republic of Djibouti","iso3"=>"DJI","iso2"=>"DJ","uni"=>"262","undp"=>"DJI","faostat"=>"72","gaul"=>"70"],
            "Dominica"=>["officialName"=>"the Commonwealth of Dominica","iso3"=>"DMA","iso2"=>"DM","uni"=>"212","undp"=>"DMA","faostat"=>"55","gaul"=>"71"],
            "Dominican Republic"=>["officialName"=>"the Dominican Republic","iso3"=>"DOM","iso2"=>"DO","uni"=>"214","undp"=>"DOM","faostat"=>"56","gaul"=>"72"],
            "Ecuador"=>["officialName"=>"the Republic of Ecuador","iso3"=>"ECU","iso2"=>"EC","uni"=>"218","undp"=>"ECU","faostat"=>"58","gaul"=>"73"],
            "Egypt"=>["officialName"=>"the Arab Republic of Egypt","iso3"=>"EGY","iso2"=>"EG","uni"=>"818","undp"=>"EGY","faostat"=>"59","gaul"=>"40765"],
            "El Salvador"=>["officialName"=>"the Republic of El Salvador","iso3"=>"SLV","iso2"=>"SV","uni"=>"222","undp"=>"SLV","faostat"=>"60","gaul"=>"75"],
            "Equatorial Guinea"=>["officialName"=>"the Republic of Equatorial Guinea","iso3"=>"GNQ","iso2"=>"GQ","uni"=>"226","undp"=>"GNQ","faostat"=>"61","gaul"=>"76"],
            "Eritrea"=>["officialName"=>"the State of Eritrea","iso3"=>"ERI","iso2"=>"ER","uni"=>"232","undp"=>"ERI","faostat"=>"178","gaul"=>"77"],
            "Estonia"=>["officialName"=>"the Republic of Estonia","iso3"=>"EST","iso2"=>"EE","uni"=>"233","undp"=>"EST","faostat"=>"63","gaul"=>"78"],
            "Eswatini"=>["officialName"=>"the Kingdom of Eswatini","iso3"=>"SWZ","iso2"=>"SZ","uni"=>"748","undp"=>"SWZ","faostat"=>"209","gaul"=>"235"],
            "Ethiopia"=>["officialName"=>"the Federal Democratic Republic of Ethiopia","iso3"=>"ETH","iso2"=>"ET","uni"=>"231","undp"=>"ETH","faostat"=>"238","gaul"=>"79"],
            "Faroe Islands"=>["officialName"=>"Faroe Islands","iso3"=>"FRO","iso2"=>"FO","uni"=>"234","undp"=>"FRO","faostat"=>"64","gaul"=>"82"],
            "Fiji"=>["officialName"=>"the Republic of Fiji","iso3"=>"FJI","iso2"=>"FJ","uni"=>"242","undp"=>"FJI","faostat"=>"66","gaul"=>"83"],
            "Finland"=>["officialName"=>"the Republic of Finland","iso3"=>"FIN","iso2"=>"FI","uni"=>"246","undp"=>"FIN","faostat"=>"67","gaul"=>"84"],
            "France"=>["officialName"=>"the French Republic","iso3"=>"FRA","iso2"=>"FR","uni"=>"250","undp"=>"FRA","faostat"=>"68","gaul"=>"85"],
            "Gabon"=>["officialName"=>"the Gabonese Republic","iso3"=>"GAB","iso2"=>"GA","uni"=>"266","undp"=>"GAB","faostat"=>"74","gaul"=>"89"],
            "Gambia"=>["officialName"=>"the Republic of the Gambia","iso3"=>"GMB","iso2"=>"GM","uni"=>"270","undp"=>"GMB","faostat"=>"75","gaul"=>"90"],
            "Georgia"=>["officialName"=>"Georgia","iso3"=>"GEO","iso2"=>"GE","uni"=>"268","undp"=>"GEO","faostat"=>"73","gaul"=>"92"],
            "Germany"=>["officialName"=>"the Federal Republic of Germany","iso3"=>"DEU","iso2"=>"DE","uni"=>"276","undp"=>"DEU","faostat"=>"79","gaul"=>"93"],
            "Ghana"=>["officialName"=>"the Republic of Ghana","iso3"=>"GHA","iso2"=>"GH","uni"=>"288","undp"=>"GHA","faostat"=>"81","gaul"=>"94"],
            "Greece"=>["officialName"=>"the Hellenic Republic","iso3"=>"GRC","iso2"=>"GR","uni"=>"300","undp"=>"GRC","faostat"=>"84","gaul"=>"97"],
            "Grenada"=>["officialName"=>"Grenada","iso3"=>"GRD","iso2"=>"GD","uni"=>"308","undp"=>"GRD","faostat"=>"86","gaul"=>"99"],
            "Guatemala"=>["officialName"=>"the Republic of Guatemala","iso3"=>"GTM","iso2"=>"GT","uni"=>"320","undp"=>"GTM","faostat"=>"89","gaul"=>"103"],
            "Guinea"=>["officialName"=>"the Republic of Guinea","iso3"=>"GIN","iso2"=>"GN","uni"=>"324","undp"=>"GIN","faostat"=>"90","gaul"=>"106"],
            "Guinea-Bissau"=>["officialName"=>"the Republic of Guinea-Bissau","iso3"=>"GNB","iso2"=>"GW","uni"=>"624","undp"=>"GNB","faostat"=>"175","gaul"=>"105"],
            "Guyana"=>["officialName"=>"the Co-operative Republic of Guyana","iso3"=>"GUY","iso2"=>"GY","uni"=>"328","undp"=>"GUY","faostat"=>"91","gaul"=>"107"],
            "Haiti"=>["officialName"=>"the Republic of Haiti","iso3"=>"HTI","iso2"=>"HT","uni"=>"332","undp"=>"HTI","faostat"=>"93","gaul"=>"108"],
            "Honduras"=>["officialName"=>"the Republic of Honduras","iso3"=>"HND","iso2"=>"HN","uni"=>"340","undp"=>"HND","faostat"=>"95","gaul"=>"111"],
            "Hungary"=>["officialName"=>"Hungary","iso3"=>"HUN","iso2"=>"HU","uni"=>"348","undp"=>"HUN","faostat"=>"97","gaul"=>"113"],
            "Iceland"=>["officialName"=>"the Republic of Iceland","iso3"=>"ISL","iso2"=>"IS","uni"=>"352","undp"=>"ISL","faostat"=>"99","gaul"=>"114"],
            "India"=>["officialName"=>"the Republic of India","iso3"=>"IND","iso2"=>"IN","uni"=>"356","undp"=>"IND","faostat"=>"100","gaul"=>"115"],
            "Indonesia"=>["officialName"=>"the Republic of Indonesia","iso3"=>"IDN","iso2"=>"ID","uni"=>"360","undp"=>"IDN","faostat"=>"101","gaul"=>"116"],
            "Iran (Islamic Republic of)"=>["officialName"=>"the Islamic Republic of Iran","iso3"=>"IRN","iso2"=>"IR","uni"=>"364","undp"=>"IRN","faostat"=>"102","gaul"=>"117"],
            "Iraq"=>["officialName"=>"the Republic of Iraq","iso3"=>"IRQ","iso2"=>"IQ","uni"=>"368","undp"=>"IRQ","faostat"=>"103","gaul"=>"118"],
            "Ireland"=>["officialName"=>"Ireland","iso3"=>"IRL","iso2"=>"IE","uni"=>"372","undp"=>"IRL","faostat"=>"104","gaul"=>"119"],
            "Israel"=>["officialName"=>"the State of Israel","iso3"=>"ISR","iso2"=>"IL","uni"=>"376","undp"=>"ISR","faostat"=>"105","gaul"=>"121"],
            "Italy"=>["officialName"=>"the Republic of Italy","iso3"=>"ITA","iso2"=>"IT","uni"=>"380","undp"=>"ITA","faostat"=>"106","gaul"=>"122"],
            "Jamaica"=>["officialName"=>"Jamaica","iso3"=>"JAM","iso2"=>"JM","uni"=>"388","undp"=>"JAM","faostat"=>"109","gaul"=>"123"],
            "Japan"=>["officialName"=>"Japan","iso3"=>"JPN","iso2"=>"JP","uni"=>"392","undp"=>"JPN","faostat"=>"110","gaul"=>"126"],
            "Jordan"=>["officialName"=>"the Hashemite Kingdom of Jordan","iso3"=>"JOR","iso2"=>"JO","uni"=>"400","undp"=>"JOR","faostat"=>"112","gaul"=>"130"],
            "Kazakhstan"=>["officialName"=>"the Republic of Kazakhstan","iso3"=>"KAZ","iso2"=>"KZ","uni"=>"398","undp"=>"KAZ","faostat"=>"108","gaul"=>"132"],
            "Kenya"=>["officialName"=>"the Republic of Kenya","iso3"=>"KEN","iso2"=>"KE","uni"=>"404","undp"=>"KEN","faostat"=>"114","gaul"=>"133"],
            "Kiribati"=>["officialName"=>"the Republic of Kiribati","iso3"=>"KIR","iso2"=>"KI","uni"=>"296","undp"=>"KIR","faostat"=>"83","gaul"=>"135"],
            "Kuwait"=>["officialName"=>"the State of Kuwait","iso3"=>"KWT","iso2"=>"KW","uni"=>"414","undp"=>"KWT","faostat"=>"118","gaul"=>"137"],
            "Kyrgyzstan"=>["officialName"=>"the Kyrgyz Republic","iso3"=>"KGZ","iso2"=>"KG","uni"=>"417","undp"=>"KGZ","faostat"=>"113","gaul"=>"138"],
            "Lao People's Democratic Republic"=>["officialName"=>"the Lao People's Democratic Republic","iso3"=>"LAO","iso2"=>"LA","uni"=>"418","undp"=>"LAO","faostat"=>"120","gaul"=>"139"],
            "Latvia"=>["officialName"=>"the Republic of Latvia","iso3"=>"LVA","iso2"=>"LV","uni"=>"428","undp"=>"LVA","faostat"=>"119","gaul"=>"140"],
            "Lebanon"=>["officialName"=>"the Lebanese Republic","iso3"=>"LBN","iso2"=>"LB","uni"=>"422","undp"=>"LBN","faostat"=>"121","gaul"=>"141"],
            "Lesotho"=>["officialName"=>"the Kingdom of Lesotho","iso3"=>"LSO","iso2"=>"LS","uni"=>"426","undp"=>"LSO","faostat"=>"122","gaul"=>"142"],
            "Liberia"=>["officialName"=>"the Republic of Liberia","iso3"=>"LBR","iso2"=>"LR","uni"=>"430","undp"=>"LBR","faostat"=>"123","gaul"=>"144"],
            "Libya"=>["officialName"=>"State of Libya","iso3"=>"LBY","iso2"=>"LY","uni"=>"434","undp"=>"LBY","faostat"=>"124","gaul"=>"145"],
            "Lithuania"=>["officialName"=>"the Republic of Lithuania","iso3"=>"LTU","iso2"=>"LT","uni"=>"440","undp"=>"LTU","faostat"=>"126","gaul"=>"147"],
            "Luxembourg"=>["officialName"=>"the Grand Duchy of Luxembourg","iso3"=>"LUX","iso2"=>"LU","uni"=>"442","undp"=>"LUX","faostat"=>"256","gaul"=>"148"],
            "Madagascar"=>["officialName"=>"the Republic of Madagascar","iso3"=>"MDG","iso2"=>"MG","uni"=>"450","undp"=>"MDG","faostat"=>"129","gaul"=>"150"],
            "Malawi"=>["officialName"=>"the Republic of Malawi","iso3"=>"MWI","iso2"=>"MW","uni"=>"454","undp"=>"MWI","faostat"=>"130","gaul"=>"152"],
            "Malaysia"=>["officialName"=>"Malaysia","iso3"=>"MYS","iso2"=>"MY","uni"=>"458","undp"=>"MYS","faostat"=>"131","gaul"=>"153"],
            "Maldives"=>["officialName"=>"the Republic of Maldives","iso3"=>"MDV","iso2"=>"MV","uni"=>"462","undp"=>"MDV","faostat"=>"132","gaul"=>"154"],
            "Mali"=>["officialName"=>"the Republic of Mali","iso3"=>"MLI","iso2"=>"ML","uni"=>"466","undp"=>"MLI","faostat"=>"133","gaul"=>"155"],
            "Malta"=>["officialName"=>"the Republic of Malta","iso3"=>"MLT","iso2"=>"MT","uni"=>"470","undp"=>"MLT","faostat"=>"134","gaul"=>"156"],
            "Marshall Islands"=>["officialName"=>"the Republic of the Marshall Islands","iso3"=>"MHL","iso2"=>"MH","uni"=>"584","undp"=>"MHL","faostat"=>"127","gaul"=>"157"],
            "Mauritania"=>["officialName"=>"the Islamic Republic of Mauritania","iso3"=>"MRT","iso2"=>"MR","uni"=>"478","undp"=>"MRT","faostat"=>"136","gaul"=>"159"],
            "Mauritius"=>["officialName"=>"the Republic of Mauritius","iso3"=>"MUS","iso2"=>"MU","uni"=>"480","undp"=>"MUS","faostat"=>"137","gaul"=>"160"],
            "Mexico"=>["officialName"=>"the United Mexican States","iso3"=>"MEX","iso2"=>"MX","uni"=>"484","undp"=>"MEX","faostat"=>"138","gaul"=>"162"],
            "Micronesia (Federated States of)"=>["officialName"=>"the Federated States of Micronesia","iso3"=>"FSM","iso2"=>"FM","uni"=>"583","undp"=>"FSM","faostat"=>"145","gaul"=>"163"],
            "Monaco"=>["officialName"=>"the Principality of Monaco","iso3"=>"MCO","iso2"=>"MC","uni"=>"492","undp"=>"MCO","faostat"=>"140","gaul"=>"166"],
            "Mongolia"=>["officialName"=>"Mongolia","iso3"=>"MNG","iso2"=>"MN","uni"=>"496","undp"=>"MNG","faostat"=>"141","gaul"=>"167"],
            "Montenegro"=>["officialName"=>"Montenegro","iso3"=>"MNE","iso2"=>"ME","uni"=>"499","undp"=>"MNE","faostat"=>"273","gaul"=>"2647"],
            "Morocco"=>["officialName"=>"the Kingdom of Morocco","iso3"=>"MAR","iso2"=>"MA","uni"=>"504","undp"=>"MAR","faostat"=>"143","gaul"=>"169"],
            "Mozambique"=>["officialName"=>"the Republic of Mozambique","iso3"=>"MOZ","iso2"=>"MZ","uni"=>"508","undp"=>"MOZ","faostat"=>"144","gaul"=>"170"],
            "Myanmar"=>["officialName"=>"the Republic of the Union of Myanmar","iso3"=>"MMR","iso2"=>"MM","uni"=>"104","undp"=>"MMR","faostat"=>"28","gaul"=>"171"],
            "Namibia"=>["officialName"=>"the Republic of Namibia","iso3"=>"NAM","iso2"=>"NA","uni"=>"516","undp"=>"NAM","faostat"=>"147","gaul"=>"172"],
            "Nauru"=>["officialName"=>"the Republic of Nauru","iso3"=>"NRU","iso2"=>"NR","uni"=>"520","undp"=>"NRU","faostat"=>"148","gaul"=>"173"],
            "Nepal"=>["officialName"=>"the Federal Democratic Republic of Nepal","iso3"=>"NPL","iso2"=>"NP","uni"=>"524","undp"=>"NPL","faostat"=>"149","gaul"=>"175"],
            "Netherlands"=>["officialName"=>"the Kingdom of the Netherlands","iso3"=>"NLD","iso2"=>"NL","uni"=>"528","undp"=>"NLD","faostat"=>"150","gaul"=>"177"],
            "New Zealand"=>["officialName"=>"New Zealand","iso3"=>"NZL","iso2"=>"NZ","uni"=>"554","undp"=>"NZL","faostat"=>"156","gaul"=>"179"],
            "Nicaragua"=>["officialName"=>"the Republic of Nicaragua","iso3"=>"NIC","iso2"=>"NI","uni"=>"558","undp"=>"NIC","faostat"=>"157","gaul"=>"180"],
            "Niger"=>["officialName"=>"the Republic of the Niger","iso3"=>"NER","iso2"=>"NE","uni"=>"562","undp"=>"NER","faostat"=>"158","gaul"=>"181"],
            "Nigeria"=>["officialName"=>"the Federal Republic of Nigeria","iso3"=>"NGA","iso2"=>"NG","uni"=>"566","undp"=>"NGA","faostat"=>"159","gaul"=>"182"],
            "Niue"=>["officialName"=>"Niue","iso3"=>"NIU","iso2"=>"NU","uni"=>"570","undp"=>"NIU","faostat"=>"160","gaul"=>"183"],
            "North Macedonia"=>["officialName"=>"the Republic of North Macedonia","iso3"=>"MKD","iso2"=>"MK","uni"=>"807","undp"=>"MKD","faostat"=>"154","gaul"=>"241"],
            "Norway"=>["officialName"=>"the Kingdom of Norway","iso3"=>"NOR","iso2"=>"NO","uni"=>"578","undp"=>"NOR","faostat"=>"162","gaul"=>"186"],
            "Oman"=>["officialName"=>"the Sultanate of Oman","iso3"=>"OMN","iso2"=>"OM","uni"=>"512","undp"=>"OMN","faostat"=>"221","gaul"=>"187"],
            "Pakistan"=>["officialName"=>"the Islamic Republic of Pakistan","iso3"=>"PAK","iso2"=>"PK","uni"=>"586","undp"=>"PAK","faostat"=>"165","gaul"=>"188"],
            "Palau"=>["officialName"=>"the Republic of Palau","iso3"=>"PLW","iso2"=>"PW","uni"=>"585","undp"=>"PLW","faostat"=>"180","gaul"=>"189"],
            "Panama"=>["officialName"=>"the Republic of Panama","iso3"=>"PAN","iso2"=>"PA","uni"=>"591","undp"=>"PAN","faostat"=>"166","gaul"=>"191"],
            "Papua New Guinea"=>["officialName"=>"Independent State of Papua New Guinea","iso3"=>"PNG","iso2"=>"PG","uni"=>"598","undp"=>"PNG","faostat"=>"168","gaul"=>"192"],
            "Paraguay"=>["officialName"=>"the Republic of Paraguay","iso3"=>"PRY","iso2"=>"PY","uni"=>"600","undp"=>"PRY","faostat"=>"169","gaul"=>"194"],
            "Peru"=>["officialName"=>"the Republic of Peru","iso3"=>"PER","iso2"=>"PE","uni"=>"604","undp"=>"PER","faostat"=>"170","gaul"=>"195"],
            "Philippines"=>["officialName"=>"the Republic of the Philippines","iso3"=>"PHL","iso2"=>"PH","uni"=>"608","undp"=>"PHL","faostat"=>"171","gaul"=>"196"],
            "Poland"=>["officialName"=>"the Republic of Poland","iso3"=>"POL","iso2"=>"PL","uni"=>"616","undp"=>"POL","faostat"=>"173","gaul"=>"198"],
            "Portugal"=>["officialName"=>"the Portuguese Republic","iso3"=>"PRT","iso2"=>"PT","uni"=>"620","undp"=>"PRT","faostat"=>"174","gaul"=>"199"],
            "Qatar"=>["officialName"=>"the State of Qatar","iso3"=>"QAT","iso2"=>"QA","uni"=>"634","undp"=>"QAT","faostat"=>"179","gaul"=>"201"],
            "Republic of Korea"=>["officialName"=>"the Republic of Korea","iso3"=>"KOR","iso2"=>"KR","uni"=>"410","undp"=>"KOR","faostat"=>"117","gaul"=>"202"],
            "Republic of Moldova"=>["officialName"=>"the Republic of Moldova","iso3"=>"MDA","iso2"=>"MD","uni"=>"498","undp"=>"MDA","faostat"=>"146","gaul"=>"165"],
            "Romania"=>["officialName"=>"Romania","iso3"=>"ROU","iso2"=>"RO","uni"=>"642","undp"=>"ROU","faostat"=>"183","gaul"=>"203"],
            "Russian Federation"=>["officialName"=>"the Russian Federation","iso3"=>"RUS","iso2"=>"RU","uni"=>"643","undp"=>"RUS","faostat"=>"185","gaul"=>"204"],
            "Rwanda"=>["officialName"=>"the Republic of Rwanda","iso3"=>"RWA","iso2"=>"RW","uni"=>"646","undp"=>"RWA","faostat"=>"184","gaul"=>"205"],
            "Saint Kitts and Nevis"=>["officialName"=>"Saint Kitts and Nevis","iso3"=>"KNA","iso2"=>"KN","uni"=>"659","undp"=>"KNA","faostat"=>"188","gaul"=>"208"],
            "Saint Lucia"=>["officialName"=>"Saint Lucia","iso3"=>"LCA","iso2"=>"LC","uni"=>"662","undp"=>"LCA","faostat"=>"189","gaul"=>"209"],
            "Saint Vincent and the Grenadines"=>["officialName"=>"Saint Vincent and the Grenadines","iso3"=>"VCT","iso2"=>"VC","uni"=>"670","undp"=>"VCT","faostat"=>"191","gaul"=>"211"],
            "Samoa"=>["officialName"=>"the Independent State of Samoa","iso3"=>"WSM","iso2"=>"WS","uni"=>"882","undp"=>"WSM","faostat"=>"244","gaul"=>"212"],
            "San Marino"=>["officialName"=>"the Republic of San Marino","iso3"=>"SMR","iso2"=>"SM","uni"=>"674","undp"=>"SMR","faostat"=>"192","gaul"=>"213"],
            "Sao Tome and Principe"=>["officialName"=>"the Democratic Republic of Sao Tome and Principe","iso3"=>"STP","iso2"=>"ST","uni"=>"678","undp"=>"STP","faostat"=>"193","gaul"=>"214"],
            "Saudi Arabia"=>["officialName"=>"the Kingdom of Saudi Arabia","iso3"=>"SAU","iso2"=>"SA","uni"=>"682","undp"=>"SAU","faostat"=>"194","gaul"=>"215"],
            "Senegal"=>["officialName"=>"the Republic of Senegal","iso3"=>"SEN","iso2"=>"SN","uni"=>"686","undp"=>"SEN","faostat"=>"195","gaul"=>"217"],
            "Serbia"=>["officialName"=>"the Republic of Serbia","iso3"=>"SRB","iso2"=>"RS","uni"=>"688","undp"=>"SRB","faostat"=>"272","gaul"=>"2648"],
            "Seychelles"=>["officialName"=>"the Republic of Seychelles","iso3"=>"SYC","iso2"=>"SC","uni"=>"690","undp"=>"SYC","faostat"=>"196","gaul"=>"220"],
            "Sierra Leone"=>["officialName"=>"the Republic of Sierra Leone","iso3"=>"SLE","iso2"=>"SL","uni"=>"694","undp"=>"SLE","faostat"=>"197","gaul"=>"221"],
            "Singapore"=>["officialName"=>"the Republic of Singapore","iso3"=>"SGP","iso2"=>"SG","uni"=>"702","undp"=>"SGP","faostat"=>"200","gaul"=>"222"],
            "Slovakia"=>["officialName"=>"the Slovak Republic","iso3"=>"SVK","iso2"=>"SK","uni"=>"703","undp"=>"SVK","faostat"=>"199","gaul"=>"223"],
            "Slovenia"=>["officialName"=>"the Republic of Slovenia","iso3"=>"SVN","iso2"=>"SI","uni"=>"705","undp"=>"SVN","faostat"=>"198","gaul"=>"224"],
            "Solomon Islands"=>["officialName"=>"Solomon Islands","iso3"=>"SLB","iso2"=>"SB","uni"=>"90","undp"=>"SLB","faostat"=>"25","gaul"=>"225"],
            "Somalia"=>["officialName"=>"the Federal Republic of Somalia","iso3"=>"SOM","iso2"=>"SO","uni"=>"706","undp"=>"SOM","faostat"=>"201","gaul"=>"226"],
            "South Africa"=>["officialName"=>"the Republic of South Africa","iso3"=>"ZAF","iso2"=>"ZA","uni"=>"710","undp"=>"ZAF","faostat"=>"202","gaul"=>"227"],
            "South Sudan"=>["officialName"=>"the Republic of South Sudan","iso3"=>"SSD","iso2"=>"SS","uni"=>"728","undp"=>"SSD","faostat"=>"277","gaul"=>"74"],
            "Spain"=>["officialName"=>"the Kingdom of Spain","iso3"=>"ESP","iso2"=>"ES","uni"=>"724","undp"=>"ESP","faostat"=>"203","gaul"=>"229"],
            "Sri Lanka"=>["officialName"=>"the Democratic Socialist Republic of Sri Lanka","iso3"=>"LKA","iso2"=>"LK","uni"=>"144","undp"=>"LKA","faostat"=>"38","gaul"=>"231"],
            "Sudan"=>["officialName"=>"the Republic of the Sudan","iso3"=>"SDN","iso2"=>"SD","uni"=>"736","undp"=>"SDN","faostat"=>"276","gaul"=>"40764"],
            "Suriname"=>["officialName"=>"the Republic of Suriname","iso3"=>"SUR","iso2"=>"SR","uni"=>"740","undp"=>"SUR","faostat"=>"207","gaul"=>"233"],
            "Sweden"=>["officialName"=>"the Kingdom of Sweden","iso3"=>"SWE","iso2"=>"SE","uni"=>"752","undp"=>"SWE","faostat"=>"210","gaul"=>"236"],
            "Switzerland"=>["officialName"=>"the Swiss Confederation","iso3"=>"CHE","iso2"=>"CH","uni"=>"756","undp"=>"CHE","faostat"=>"211","gaul"=>"237"],
            "Syrian Arab Republic"=>["officialName"=>"the Syrian Arab Republic","iso3"=>"SYR","iso2"=>"SY","uni"=>"760","undp"=>"SYR","faostat"=>"212","gaul"=>"238"],
            "Tajikistan"=>["officialName"=>"the Republic of Tajikistan","iso3"=>"TJK","iso2"=>"TJ","uni"=>"762","undp"=>"TJK","faostat"=>"208","gaul"=>"239"],
            "Thailand"=>["officialName"=>"the Kingdom of Thailand","iso3"=>"THA","iso2"=>"TH","uni"=>"764","undp"=>"THA","faostat"=>"216","gaul"=>"240"],
            "Timor-Leste"=>["officialName"=>"the Democratic Republic of Timor-Leste","iso3"=>"TLS","iso2"=>"TL","uni"=>"626","undp"=>"TLS","faostat"=>"176","gaul"=>"242"],
            "Togo"=>["officialName"=>"the Togolese Republic","iso3"=>"TGO","iso2"=>"TG","uni"=>"768","undp"=>"TGO","faostat"=>"217","gaul"=>"243"],
            "Tokelau"=>["officialName"=>"Tokelau","iso3"=>"TKL","iso2"=>"TK","uni"=>"772","undp"=>"TKL","faostat"=>"218","gaul"=>"244"],
            "Tonga"=>["officialName"=>"the Kingdom of Tonga","iso3"=>"TON","iso2"=>"TO","uni"=>"776","undp"=>"TON","faostat"=>"219","gaul"=>"245"],
            "Trinidad and Tobago"=>["officialName"=>"the Republic of Trinidad and Tobago","iso3"=>"TTO","iso2"=>"TT","uni"=>"780","undp"=>"TTO","faostat"=>"220","gaul"=>"246"],
            "Tunisia"=>["officialName"=>"the Republic of Tunisia","iso3"=>"TUN","iso2"=>"TN","uni"=>"788","undp"=>"TUN","faostat"=>"222","gaul"=>"248"],
            "Turkey"=>["officialName"=>"the Republic of Turkey","iso3"=>"TUR","iso2"=>"TR","uni"=>"792","undp"=>"TUR","faostat"=>"223","gaul"=>"249"],
            "Turkmenistan"=>["officialName"=>"Turkmenistan","iso3"=>"TKM","iso2"=>"TM","uni"=>"795","undp"=>"TKM","faostat"=>"213","gaul"=>"250"],
            "Tuvalu"=>["officialName"=>"Tuvalu","iso3"=>"TUV","iso2"=>"TV","uni"=>"798","undp"=>"TUV","faostat"=>"227","gaul"=>"252"],
            "Uganda"=>["officialName"=>"the Republic of Uganda","iso3"=>"UGA","iso2"=>"UG","uni"=>"800","undp"=>"UGA","faostat"=>"226","gaul"=>"253"],
            "Ukraine"=>["officialName"=>"Ukraine","iso3"=>"UKR","iso2"=>"UA","uni"=>"804","undp"=>"UKR","faostat"=>"230","gaul"=>"254"],
            "United Arab Emirates"=>["officialName"=>"the United Arab Emirates","iso3"=>"ARE","iso2"=>"AE","uni"=>"784","undp"=>"ARE","faostat"=>"225","gaul"=>"255"],
            "United Kingdom of Great Britain and Northern Ireland"=>["officialName"=>"the United Kingdom of Great Britain and Northern Ireland","iso3"=>"GBR","iso2"=>"GB","uni"=>"826","undp"=>"GBR","faostat"=>"229","gaul"=>"256"],
            "United Republic of Tanzania"=>["officialName"=>"the United Republic of Tanzania","iso3"=>"TZA","iso2"=>"TZ","uni"=>"834","undp"=>"TZA","faostat"=>"215","gaul"=>"257"],
            "United States of America"=>["officialName"=>"the United States of America","iso3"=>"USA","iso2"=>"US","uni"=>"840","undp"=>"USA","faostat"=>"231","gaul"=>"259"],
            "Uruguay"=>["officialName"=>"the Eastern Republic of Uruguay","iso3"=>"URY","iso2"=>"UY","uni"=>"858","undp"=>"URY","faostat"=>"234","gaul"=>"260"],
            "Uzbekistan"=>["officialName"=>"the Republic of Uzbekistan","iso3"=>"UZB","iso2"=>"UZ","uni"=>"860","undp"=>"UZB","faostat"=>"235","gaul"=>"261"],
            "Vanuatu"=>["officialName"=>"the Republic of Vanuatu","iso3"=>"VUT","iso2"=>"VU","uni"=>"548","undp"=>"VUT","faostat"=>"155","gaul"=>"262"],
            "Venezuela (Bolivarian Republic of)"=>["officialName"=>"the Bolivarian Republic of Venezuela","iso3"=>"VEN","iso2"=>"VE","uni"=>"862","undp"=>"VEN","faostat"=>"236","gaul"=>"263"],
            "Viet Nam"=>["officialName"=>"the Socialist Republic of Viet Nam","iso3"=>"VNM","iso2"=>"VN","uni"=>"704","undp"=>"VNM","faostat"=>"237","gaul"=>"264"],
            "Yemen"=>["officialName"=>"the Republic of Yemen","iso3"=>"YEM","iso2"=>"YE","uni"=>"887","undp"=>"YEM","faostat"=>"249","gaul"=>"269"],
            "Zambia"=>["officialName"=>"the Republic of Zambia","iso3"=>"ZMB","iso2"=>"ZM","uni"=>"894","undp"=>"ZMB","faostat"=>"251","gaul"=>"270"],
            "Zimbabwe"=>["officialName"=>"the Republic of Zimbabwe","iso3"=>"ZWE","iso2"=>"ZW","uni"=>"716","undp"=>"ZWE","faostat"=>"181","gaul"=>"271"]
        ];

        foreach ($countries as $term => $metas) {
            TaxonomyManager::register($term, 'countries', null, $metas);
        }
    }
}
